//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class applicant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public applicant()
        {
            this.details_interview = new HashSet<details_interview>();
        }

        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        [Display(Name = "Applicant ID")]
        public string id { get; set; }
        [Display(Name = "Target")]
        [MaxLength(500)]
        public string target { get; set; }
        [Display(Name = "Experiences")]
        [MaxLength(1000)]
        public string experience { get; set; }
        [Display(Name = "Education")]
        [MaxLength(1000)]
        public string education { get; set; }
        [Display(Name = "Skills")]
        [MaxLength(255)]
        public string skills { get; set; }
        [Display(Name = "Status")]
        public string status { get; set; }
        [Required]
        [Display(Name = "Register At")]

        public System.DateTime createAt { get; set; }
        [Required]
        [Display(Name = "Phone")]
        [DataType(DataType.PhoneNumber)]
        [MinLength(9)]
        public string phone { get; set; }
        [Display(Name = "Photo")]
        [MaxLength(255)]
        [DataType(DataType.Upload)]
        [RegularExpression(@"([a-zA-Z0-9\s_\.-:])+(.png|.jpg|.gif)$", ErrorMessage = "Yêu cầu nhập đúng định dạng ảnh .png|.jpg|.gif")]
        public string image { get; set; }
        [Display(Name = "User name")]
        public string username { get; set; }
        [RegularExpression(@"^((?=.*[a-z])|(?=.*[A-Z])|(?=.*\d)).{5,}$", ErrorMessage = "Password must have at least 5 characters and no special signs.")]
        //[MinLength(5)]
        [Display(Name = "Password")]
        public string password { get; set; }
        [Required]
        [Display(Name = "Applicant name")]
        public string display_name { get; set; }
        [Required]
        [RegularExpression(@"[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", ErrorMessage = "Email is not valid")]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<details_interview> details_interview { get; set; }
    }
}
