//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class details_interview : IValidatableObject
    {
        [Key, Column(Order = 1)]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }
        [Required]
        [Display(Name = "Applicant")]
        public string applicantId { get; set; }
        [Required]
        [Display(Name = "Vacancy")]
        public string vacancyId { get; set; }
        [Required]
        [Display(Name = "Interviewer")]
        public string employeeId { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-ddThh:mm}", ApplyFormatInEditMode = true)]
        [Display(Name = "Day")]
        public System.DateTime time { get; set; }
        [Display(Name = "Status")]
        public string status { get; set; }
    
        public virtual applicant applicant { get; set; }
        public virtual employee employee { get; set; }
        public virtual vacancy vacancy { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (time < DateTime.Now)
            {
                yield return new ValidationResult(
                    "Interview date must later than now.",
                    new[] { nameof(time) });
            }
        }
    }
}
